### ISSUE TITLE
Unminify grammar string

### ISSUE THREAD

**Issue by dbarowy** [dbarowy/gCheckCell#2]
The grammar is a bit unreadable.  We need to be able to maintain this moving forward.  Can you format this so it is readable?

**Comment by atoader** [comment]
Is the formatting in doc/oldExcelGrammar.pegjs ok? I created the file PEGParser.js from this grammar using the command  pegjs.cmd --export-var PEGParser .\oldExcelGrammar.pegjs PEGParser.js.

**Comment by dbarowy** [comment]
Great!  I didn't see this before.  I wasn't looking in the docs directory.  Looks good to me.
